### ISSUE TITLE
TodoList

### ISSUE THREAD

**Issue by jaykop** [jaykop/How#14]
1. Path findinig - polish
2. Save feature - done
3. Component  - done
4. Logic system - done
4.5 InputManager
5. Load thread
6. Json - done
7. Punch system
8. Time manipulation
9. Refine code - doing
10. comment - doing

**Comment by jaykop** [comment]
1. Path-findinig
2. InputManager
3. Load thread
4. Punch system
5. Time manipulation
6. Refine code - doing
7. comment - doing

**Comment by edh007** [comment]
1. Path Finding
2. Ray Casting - Rectangle
3. Run/Walk
4. Enemy AI Design
5. Refactoring Traps
6. Player Feature - Delete gun & Make delay on searching
7. Level Editor
