### ISSUE TITLE
Graphic tasks

### ISSUE THREAD

**Issue by jaykop** [jaykop/How#3]
1. Color - done
2. Transparancy - done
3. Particle
   //For now.

**Comment by jaykop** [comment]
0. Z Ordering bug
1. Camera position, rotation setting function
2. Particle

**Comment by edh007** [comment]
1. Z ordering - Solved.
2. Camera position - Rotation - until tomorrow
3. free image loading system - until tomorrow
4. only text ouput don't work. - need help.
5. Particle, light, resolution - Next work.

**Comment by jaykop** [comment]
Animation flip!
